version: "3.7"

services:
  db:
    container_name: your-web-app_db
    build:
      context: ./docker-postgis
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/data/:/mnt/
    ports:
      - ${POSTGRES_PORT}:5432

  app:
    container_name: your-web-app_app
    build:
      context: ./docker-rshiny
    # image: fineprint/your-web-app
    restart: always
    ports:
      - ${SHINY_PORT}:80
    volumes:
      - ./app:/srv/shiny-server

volumes:
  pgdata:
    driver: local
